name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Login to Dockerhub
      env:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USERNMAME -p $DOCKER_PASSWORD 
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag amaurybsouza/action:$(date +%s)
      
    - name: Docker Push
      run: docker push amaurybsouza/action
